# Generated by Django 5.0 on 2024-01-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
