# Generated by Django 5.0 on 2024-01-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data',
            new_name='date',
        ),
    ]
